apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wavp532kb-python 
  janus-idp.io/tekton: wavp532kb-python
  backstage.io/kubernetes-id: wavp532kb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wavp532kb-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  